name: "KBO Knit: Preview"

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [closed]

permissions:
  contents: read
  pull-requests: read
  actions: read
  packages: read
  id-token: write

jobs:
  preview:
    if: github.event_name == 'pull_request_target' || (github.event.issue.pull_request && github.event.comment.user.type != 'Bot')
    uses: fleetia/fleetia-bot/.github/workflows/preview.yml@39040897ff21a0d3cecb09261f089b9ccd67b7d1
    with:
      bot-ref: 39040897ff21a0d3cecb09261f089b9ccd67b7d1
    secrets:
      FLEETIA_BOT_PRIVATE_KEY: ${{ secrets.FLEETIA_BOT_PRIVATE_KEY }}
